Test: Qodana가 제대로 동작하는지 테스트

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,6 +29,17 @@ jobs:
           distribution: 'corretto'
           cache: 'gradle'
 
+      - name: Verify Gradle Wrapper
+        run: |
+          if [ ! -f ./gradlew ]; then
+            echo "Gradle Wrapper not found!"
+            exit 1
+          fi
+          if [ ! -f ./gradle/wrapper/gradle-wrapper.properties ]; then
+            echo "Gradle Wrapper properties file not found!"
+            exit 1
+          fi
+
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
